# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: tf-backend-storage
- name: ResourceGroup
  value: '$(RgNamePrefix)-$(Location)'

steps:
- task: AzureCLI@2
  displayName: 'Backend Storage Account'
  inputs:
    azureSubscription: 'k8sProduction'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --location $(Location) --name $(ResourceGroup)
      az storage account create --name $(StorageAccountName) --resource-group $(ResourceGroup) --location $(Location) --sku Standard_LRS
      az lock create --name lockName --resource-group $(ResourceGroup) --lock-type CanNotDelete
      az lock create --name lockName --resource-group $(ResourceGroup) --lock-type CanNotDelete --resource-type 'Microsoft.Storage/storageAccounts' --resource $(StorageAccountName)
      STORAGE_ACCOUNT_KEY=$(az storage account keys list -g $(ResourceGroup) -n $(StorageAccountName) | jq ".[0].value" -r)
      echo "setting storage account key variable" echo "##vso[task.setvariable variable=ARM_ACCESS_KEY;issecret=true]$STORAGE_ACCOUNT_KEY" 